package br.com.gerenciamento.acceptance;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class TesteTest {
  private WebDriver driver;
  private Map<String, Object> vars;

  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void teste() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Clique aqui para se cadastrar")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("teste25@ufape.com");
    driver.findElement(By.id("user")).click();
    driver.findElement(By.id("user")).sendKeys("teste25");
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("teste");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.id("user")).click();
    driver.findElement(By.id("user")).sendKeys("teste25");
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("teste");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("CADASTRAR ALUNO")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col-md-6")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("teste25");
    driver.findElement(By.id("curso")).click();
    {
      WebElement dropdown = driver.findElement(By.id("curso"));
      dropdown.findElement(By.xpath("//option[. = 'BIOMEDICINA']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.id("status")).click();
    driver.findElement(By.id("turno")).click();
    {
      WebElement dropdown = driver.findElement(By.id("turno"));
      dropdown.findElement(By.xpath("//option[. = 'NOTURNO']")).click();
    }
    driver.findElement(By.cssSelector(".btn-outline-success")).click();
  }
}
